version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/

hooks:
  ApplicationStop:
    - location: test_script/appstop.sh
      timeout: 6000
  BeforeInstall:
    - location: test_script/beforeinstall.sh
      timeout: 6000
  AfterInstall:
    - location: test_script/afterinstall.sh
      timeout: 6000
  ApplicationStart:
    - location: test_script/appstart.sh
      timeout: 6000
  
