version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # copy the contents of /build to S3
      - echo Build completed successfully
      - 
artifacts:
  files:
    - '**/*'
  base-directory: build


# aws deploy create-deployment --application-name hyla-root-ui --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name hyla-root-ui-groups --description "My demo deployment" --ignore-application-stop-failures --s3-location bucket=cscid-django,bundleType=zip,key=rooter-ui 

# less /opt/codedeploy-agent/deployment-root/hyla-root-ui-groups/d-OV9E00OW2/logs/scripts.log