const GET_NORMAL_REQUEST = 'GET_NORMAL_REQUEST';
const GET_NORMAL_REQUEST_SUCCESS = 'GET_NORMAL_REQUEST_SUCCESS';
const GET_NORMAL_REQUEST_ERROR = 'GET_NORMAL_REQUEST_ERROR';
const ADD_NORMAL_REQUEST = 'ADD_NORMAL_REQUEST';
const ADD_NORMAL_REQUEST_ERROR = 'ADD_NORMAL_REQUEST_ERROR';
const ADD_NORMAL_REQUEST_SUCCESS = 'ADD_NORMAL_REQUEST_SUCCESS';
export {
  GET_NORMAL_REQUEST, GET_NORMAL_REQUEST_SUCCESS, GET_NORMAL_REQUEST_ERROR,
  ADD_NORMAL_REQUEST,ADD_NORMAL_REQUEST_ERROR, ADD_NORMAL_REQUEST_SUCCESS
};
