const GET_DEPLOYMENT_REQUEST = 'GET_DEPLOYMENT_REQUEST';
const GET_DEPLOYMENT_REQUEST_SUCCESS = 'GET_DEPLOYMENT_REQUEST_SUCCESS';
const GET_DEPLOYMENT_REQUEST_ERROR = 'GET_DEPLOYMENT_REQUEST_ERROR';
const ADD_DEPLOYMENT_REQUEST = 'ADD_DEPLOYMENT_REQUEST';
const UPDATE_DEPLOYMENT_REQUEST = 'UPDATE_DEPLOYMENT_REQUEST';
const UPDATE_DEPLOYMENT_REQUEST_SUCCESS = 'UPDATE_DEPLOYMENT_REQUEST_SUCCESS';
const UPDATE_DEPLOYMENT_REQUEST_ERROR = 'UPDATE_DEPLOYMENT_REQUEST_ERROR';

export {
  GET_DEPLOYMENT_REQUEST, GET_DEPLOYMENT_REQUEST_SUCCESS, GET_DEPLOYMENT_REQUEST_ERROR,
  ADD_DEPLOYMENT_REQUEST, UPDATE_DEPLOYMENT_REQUEST, UPDATE_DEPLOYMENT_REQUEST_SUCCESS, UPDATE_DEPLOYMENT_REQUEST_ERROR
};
