
const GET_ENVIRONMENT_INFO = 'GET_ENVIRONMENT_INFO';
const GET_ENVIRONMENT_INFO_SUCCESS = 'GET_ENVIRONMENT_INFO_SUCCESS';
const GET_ENVIRONMENT_INFO_ERROR = 'GET_DASHBOARD_INFO_ERROR';

const GET_PROGRAME_DETAIL_INFO = 'GET_PROGRAME_DETAIL_INFO';
const GET_PROGRAME_DETAIL_INFO_SUCCESS = 'GET_PROGRAME_DETAIL_INFO_SUCCESS';
const GET_PROGRAME_DETAIL_INFO_ERROR = 'GET_PROGRAME_DETAIL_INFO_ERROR';

const GET_PROGRAME_TYPE_DETAIL_INFO = 'GET_PROGRAME_TYPE_DETAIL_INFO';
const GET_PROGRAME_TYPE_DETAIL_INFO_SUCCESS = 'GET_PROGRAME_TYPE_DETAIL_INFO_SUCCESS';
const GET_PROGRAME_TYPE_DETAIL_INFO_ERROR = 'GET_PROGRAME_TYPE_DETAIL_INFO_ERROR';

const GET_APP_LIST_INFO = 'GET_APP_LIST_INFO';
const GET_APP_LIST_INFO_SUCCESS = 'GET_APP_LIST_INFO_SUCCESS';
const GET_APP_LIST_INFO_ERROR = 'GET_APP_LIST_INFO_ERROR';

const GET_APP_PROGRAM_LIST_INFO = 'GET_APP_PROGRAM_LIST_INFO';
const GET_APP_PROGRAM_LIST_INFO_SUCCESS = 'GET_APP_PROGRAM_LIST_INFO_SUCCESS';
const GET_APP_PROGRAM_LIST_INFO_ERROR = 'GET_APP_PROGRAM_LIST_INFO_ERROR';




export {
  GET_ENVIRONMENT_INFO, GET_ENVIRONMENT_INFO_SUCCESS, GET_ENVIRONMENT_INFO_ERROR,
  GET_PROGRAME_DETAIL_INFO, GET_PROGRAME_DETAIL_INFO_SUCCESS, GET_PROGRAME_DETAIL_INFO_ERROR,
  GET_PROGRAME_TYPE_DETAIL_INFO, GET_PROGRAME_TYPE_DETAIL_INFO_SUCCESS, GET_PROGRAME_TYPE_DETAIL_INFO_ERROR,
  GET_APP_LIST_INFO, GET_APP_LIST_INFO_SUCCESS, GET_APP_LIST_INFO_ERROR,
  GET_APP_PROGRAM_LIST_INFO, GET_APP_PROGRAM_LIST_INFO_SUCCESS, GET_APP_PROGRAM_LIST_INFO_ERROR
};
